# Generated by Django 3.0 on 2023-01-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230113_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='regles',
            field=models.ManyToManyField(blank=True, to='api.Regle'),
        ),
        migrations.AlterField(
            model_name='regle',
            name='exercices',
            field=models.ManyToManyField(blank=True, to='api.Exercice'),
        ),
    ]
