# Generated by Django 3.0 on 2023-01-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230111_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='adresse_mail',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
