# Generated by Django 3.0 on 2023-02-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230221_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='ue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.UE'),
        ),
    ]
