# Generated by Django 3.0 on 2023-01-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230111_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='adresse_mail',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
