# Generated by Django 3.0 on 2023-02-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230111_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
