# Generated by Django 3.0 on 2023-02-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230220_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='regles',
            field=models.ManyToManyField(blank=True, to='api.Regle'),
        ),
        migrations.AlterField(
            model_name='regle',
            name='exercices',
            field=models.ManyToManyField(blank=True, to='api.Exercice'),
        ),
    ]
